- name: loops
  hosts: mongodb
  tasks:
    - name: print thr variables
      ansible.builtin.debug:
        msg: "print out put {{item}}"
      loop:
        - naga
        - prasanna
        - kumar
      