- name: creating a user if it is not using condition
  hosts: mongodb
  tasks:
  - name: check the user first
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: True
  - name: store the output
    ansible.builtin.debug:
      msg: "output is {{output}}"
  - name: print exist user
    ansible.builtin.debug:
      msg: "output is {{output.rc}}"
    when: output.rc != 0
  - name: create user
    become: yes
    ansible.builtin.user:
      name: roboshop
