- name: declaring variables at top level
  hosts: monodb
  vars:
    name: naga prasanna kumar
    course: devops
  tasks:
  - name: printing the variables
    ansible.builtin.debug:
      msg: "my self {{name}} is preparing {{course}}"
    vars:
      name: prasanna
      course: aws
      ansible.builtin.debug:
        msg: "my self {{name}} is preparing {{course}}"